version: '3.8'

services:
  app:
    image: ${DOCKER_REGISTRY-}app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
  web:
    image: nginx
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "8081:8081"